### ISSUE TITLE
Feature request: implement authentication, authorization

### ISSUE THREAD

**Issue by Aaronontheweb** [davidfowl/Todos#1]
Given that authentication / authorization / account management is usually where the upfront technical cost of modern web applications explodes out of control, I would love to see a similarly minimalist example of how to implement those in this application.

**Comment by davidfowl** [comment]
What kind? With user account stored locally or externally?

**Comment by Aaronontheweb** [comment]
Externally, ideally with credentials provided by an external provider like Azure AD

**Comment by Aaronontheweb** [comment]
Fleshing this out now that I'm back at my computer, I would like to see:

- External auth provider, like Azure AD, used to provide SSO plus claims
- Claims based authorization on specific routes
- User-specific to dos, so I suppose that would be multi-tenant, just to help separate out who can see what

**Comment by deedubb** [comment]
I think a minimum application tutorial/sample should also include local accounts in the same database. Would you like me to open a seperate ticket?

**Comment by davidfowl** [comment]
You can also send a PR and I’ll clean it up 😁

**Comment by PureKrome** [comment]
External auth would be awesome. including using JWT's for claims.

The auth story is sooooooooooooooooooo hard to get right.

**Comment by davidfowl** [comment]
How would you want the auth to work for a backend API?

**Comment by PureKrome** [comment]
Here's something I was experimenting with.

- Auth0 to authenticate (they store my u/p) [can be ANY 3rd party 'Authentication Provider']
- My own app then 'saves' the user info (creates the user account) and therefore creates the JWT with claims.
- Subsequent queries include JWT in bearer token.

Please don't tell Barry. It could kill him.


[startup.cs](https://github.com/PureKrome/DelegatedAuthentication/blob/master/src/DelegatedAuthentication.WebApi/Startup.cs#L38)

```
// How we create our own user/account and custom claims.
var authenticationService = new AuthenticationService<Auth0Jwt, CustomJwt, CustomAuthenticationOptions, Account>(applicationSettings.Auth0Secret,
                                                                                                                             applicationSettings.CustomSecret);
services.AddSingleton<IAuthenticationService<Auth0Jwt, CustomJwt, CustomAuthenticationOptions, Account>>(authenticationService);

// Normal JWT wiring up.
services.AddCustomJwtAuthentication(applicationSettings.CustomAudience,
                                    applicationSettings.CustomAuthority,
                                    applicationSettings.CustomSecret);
```
[AuthenticationService](https://github.com/PureKrome/DelegatedAuthentication/blob/master/src/DelegatedAuthentication/AuthenticationService.cs#L39) - code that :
 
- validates the Auth0 (or any other JWT), grabs details from it 
- creates / retrieves existing account
- creates new JWT with claims


The idea is that:

- don't want to store any u/p
- don't want to store my user details OUTSIDE/ELSEWHERE and therefore needs clucky api calls to get user data.
- don't want to SYNC data outside (again ... don't want it outside).
- want to use JWT's with claims
- want to try and keep this SIMPLE ... like your TODO.

please don't be too brutal, at my code :/ 

That repo is still a WIP ... with respect to final tweaks and documentation.

**Comment by davidfowl** [comment]
I think that's super nice. Though it doesn't require a custom auth handler 😄. Usually today we do external auth, the on the callback url path you can transfer the claims to a cookie. It sounds like instead you're issuing a jwt token with those claims (which is the moral equivalent).
